import = ['C:\Users\zach\AppData/Roaming/alacritty/alacritty-windows.toml']
live_config_reload = true

[colors.bright]
black = "#696969"
blue = "#007FFF"
cyan = "#00CCCC"
green = "#03C03C"
magenta = "#FF1493"
red = "#ff5458"
white = "#FFFAFA"
yellow = "#FDFF00"

[colors.normal]
black = "#10100E"
blue = "#0087BD"
cyan = "#20B2AA"
green = "#009F6B"
magenta = "#ae81ff"
red = "#ff8080"
white = "#C6C6C4"
yellow = "#FFD700"

[colors.primary]
background = "#000000"
foreground = "#C6C6C4"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 16

[font.normal]
family = "Inconsolata Nerd Font"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[window]
decorations = "full"
dynamic_title = false
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"
